language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests --config=setup-ci.cfg

deploy:
  - provider: codedeploy
      wait-until-deployed: true
    revision_type: github
    access_key_id: AKIAIREOSHVK2PRY5LYQ
    secret_access_key: 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
    bucket: zeus.bucket.1
    key: latest/zeus.zip
    application: zeus
    deployment_group: zeus-ci-dev
    region: us-west-2
